service:
  name: serverless-ts-apollo-server

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  patterns:
    - schema.graphql
